# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for web_aim.py — Valorant AI 自瞄 (onedir mode)"""

import os
from pathlib import Path

_here = Path(SPECPATH).resolve()

a = Analysis(
    ['web_aim.py'],
    pathex=[str(_here)],
    binaries=[],
    datas=[
        ('configs', 'configs'),
        ('fitted_params.json', '.'),
    ],
    hiddenimports=[
        'ultralytics.nn',
        'ultralytics.nn.modules',
        'ultralytics.nn.modules.block',
        'ultralytics.nn.modules.conv',
        'ultralytics.nn.modules.head',
        'ultralytics.nn.tasks',
        'ultralytics.utils',
        'ultralytics.utils.callbacks',
        'ultralytics.utils.metrics',
        'ultralytics.utils.loss',
        'ultralytics.utils.tal',
        'ultralytics.utils.ops',
        'ultralytics.utils.checks',
        'ultralytics.utils.downloads',
        'ultralytics.utils.files',
        'ultralytics.utils.instance',
        'ultralytics.utils.patches',
        'ultralytics.utils.plotting',
        'ultralytics.utils.torch_utils',
        'ultralytics.data',
        'ultralytics.data.utils',
        'ultralytics.data.build',
        'ultralytics.data.dataset',
        'ultralytics.data.loaders',
        'ultralytics.data.augment',
        'ultralytics.engine',
        'ultralytics.engine.model',
        'ultralytics.engine.results',
        'ultralytics.engine.trainer',
        'ultralytics.engine.validator',
        'ultralytics.engine.predictor',
        'ultralytics.cfg',
        'torch',
        'torch.utils.cpp_extension',
        'torchvision',
        'torchvision.models',
        'torchvision.ops',
        'torchvision.transforms',
        'cv2',
        'cv2.data',
        'flask',
        'werkzeug',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'unicodedata',
        'numpy',
        'mss',
        'PIL',
        'yaml',
        'tqdm',
        'matplotlib',
        'psutil',
        'pywinusb.hid',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'tcl',
        'matplotlib.tests',
        'scipy',
        'pandas',
        'IPython',
        'jupyter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='WebAim',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='WebAim',
)
